apiVersion : apps/v1
kind: Deployment
metadata:
  name: "avibcluster-928c"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "avibcluster-928c"
  template:
    metadata:
      labels:
        app: "avibcluster-928c"
    spec:
      containers:
        - name: "avibcluster-928c"
          image: "avibregistry.azurecr.io/avibcluster928c"
          ports:
          - containerPort: 1617