apiVersion: v1
kind: Service
metadata:
    name: "avibcluster-145a"
    labels:
        app: "avibcluster-145a"
spec:
    type: LoadBalancer
    ports:
    - port: 1617
      targetPort: 1617
      protocol: TCP
      name: http
    selector:
        app: "avibcluster-145a"