
# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
    steps:
    - uses: actions/checkout@v2
    - name: Cache node modules
      uses: actions/cache@v2.1.2
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: ~/.npm
        # An explicit key for restoring and saving the cache
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }} 
        # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
        restore-keys: |
            ${{ runner.os }}-node-
            
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    
    
    
